/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JBoss EAP 7.1.0.GA (WildFly Core 3.0.10.Final-redhat-1) - 1.4.18.Final-redhat-2
 * Generated at: 2021-03-24 01:17:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frame.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.eframework.core.config.systemconfig.SystemConfig;
import com.eframework.core.xml.config.systemconfig.SystemConfigXML;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/resources/extend.inc", Long.valueOf(1607931302000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.eframework.core.config.systemconfig.SystemConfig");
    _jspx_imports_classes.add("com.eframework.core.xml.config.systemconfig.SystemConfigXML");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fe_005fmainPage_0026_005floading;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fe_005fmainPage_0026_005floading = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fe_005fmainPage_0026_005floading.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String root = request.getContextPath();
    String programName =  SystemConfig.getConfigXML().getProgramName();
    if(programName==null||"".equals(programName)){
        programName = "系统首页";
    }
    String welcomeUrl =    (String) request.getAttribute("welcomeUrl"); //用户自定义欢迎页面
    String welcomeJs =  (String) request.getAttribute("welcomeJs");     //用户自定义欢迎页面JS
    String jsVersion= SystemConfig.getConfigXML().getJsVersion();



    String headUrl = (String) request.getAttribute("headUrl");          //用户自定义头部工作条
    if(headUrl==null){
        headUrl="head.jsp";
    }
    String headJs = (String) request.getAttribute("headJs");            //用户自定义头部工作条JS
    if(headJs==null){
        headJs="";
    }


    String initMenuNo = (String) request.getAttribute("initMenuNo");       //从门户直接调入本系统菜单（菜单编号）
    if(initMenuNo==null){
        initMenuNo="";
    }
    String initMenuName = (String) request.getAttribute("initMenuName");    //从门户直接调入本系统菜单（菜单名称）
    if(initMenuName==null){
        initMenuName="";
    }
    String initMenuUrl = (String) request.getAttribute("initMenuUrl");      //从门户直接调入本系统菜单（url）
    if(initMenuUrl==null){
        initMenuUrl="";
    }
    String initMenuJs = (String) request.getAttribute("initMenuJs");        //从门户直接调入本系统菜单（js）
    if(initMenuJs==null){
        initMenuJs="";
    }

    String frameControlUserId = (String) request.getAttribute("userId");        //userId
    if(frameControlUserId==null){
        frameControlUserId="";
    }


    String frameCrypto = (String) request.getAttribute("crypto");        //crypot
    if(frameCrypto==null){
        frameCrypto="false";
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 9]>         <html class=\"ie9 no-focus\" data-ng-app=\"app\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 9]><!--> <html class=\"no-focus\" data-ng-app=\"app\" lang=\"en\"> <!--<![endif]-->\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>");
      out.print(programName);
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("        <meta name=\"description\" content=\"OneUI - Admin Dashboard Template & UI Framework created by pixelcave and published on Themeforest\">\r\n");
      out.write("        <meta name=\"author\" content=\"pixelcave\">\r\n");
      out.write("        <meta name=\"robots\" content=\"noindex, nofollow\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1.0\">\r\n");
      out.write("        <meta name=\"apple-mobile-web-app-capable\" content=\"yes\"/>\r\n");
      out.write("        <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("        <!-- Icons -->\r\n");
      out.write("        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"assets/img/favicons/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"assets/img/favicons/favicon-16x16.png\" sizes=\"16x16\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"assets/img/favicons/favicon-32x32.png\" sizes=\"32x32\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"assets/img/favicons/favicon-96x96.png\" sizes=\"96x96\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"assets/img/favicons/favicon-160x160.png\" sizes=\"160x160\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"assets/img/favicons/favicon-192x192.png\" sizes=\"192x192\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/img/favicons/apple-touch-icon-57x57.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/img/favicons/apple-touch-icon-60x60.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/img/favicons/apple-touch-icon-72x72.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/img/favicons/apple-touch-icon-76x76.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/img/favicons/apple-touch-icon-114x114.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/img/favicons/apple-touch-icon-120x120.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/img/favicons/apple-touch-icon-144x144.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/img/favicons/apple-touch-icon-152x152.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/img/favicons/apple-touch-icon-180x180.png\">\r\n");
      out.write("        <!-- END Icons -->\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body data-ng-controller=\"AppCtrl\" >\r\n");
      out.write("\r\n");
      out.write("        <script >\r\n");
      out.write("            var welcomeUrl = \"");
      out.print(root+welcomeUrl);
      out.write("\";\r\n");
      out.write("            var welcomeJs = \"");
      out.print(root+welcomeJs);
      out.write("\";\r\n");
      out.write("            var initMenuNo = \"");
      out.print(initMenuNo);
      out.write("\";\r\n");
      out.write("            var initMenuName= \"");
      out.print(initMenuName);
      out.write("\";\r\n");
      out.write("            var initMenuUrl= \"");
      out.print(initMenuUrl);
      out.write("\";\r\n");
      out.write("            var initMenuJs= [\"");
      out.print(initMenuJs);
      out.write("\"];\r\n");
      out.write("            var frameControlUserId= \"");
      out.print(frameControlUserId);
      out.write("\";\r\n");
      out.write("            var frameCrypto= \"");
      out.print(frameCrypto);
      out.write("\";\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        ");
      //  e:mainPage
      com.eframework.web.tags.MainPageTag _jspx_th_e_005fmainPage_005f0 = (com.eframework.web.tags.MainPageTag) _005fjspx_005ftagPool_005fe_005fmainPage_0026_005floading.get(com.eframework.web.tags.MainPageTag.class);
      _jspx_th_e_005fmainPage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_e_005fmainPage_005f0.setParent(null);
      // /frame/index/index.jsp(101,8) name = loading type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_e_005fmainPage_005f0.setLoading("true");
      int _jspx_eval_e_005fmainPage_005f0 = _jspx_th_e_005fmainPage_005f0.doStartTag();
      if (_jspx_eval_e_005fmainPage_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("        <!-- Page Container -->\r\n");
          out.write("        <!-- You can update template settings or enable local storage feature in js/app.js -> 'AppCtrl' controller () -->\r\n");
          out.write("        <div id=\"page-container\" data-ng-class=\"{\r\n");
          out.write("            'sidebar-l': oneui.settings.sidebarLeft,\r\n");
          out.write("            'sidebar-r': ! oneui.settings.sidebarLeft,\r\n");
          out.write("            'sidebar-o': oneui.settings.sidebarOpen,\r\n");
          out.write("            'sidebar-o-xs': oneui.settings.sidebarOpenXs,\r\n");
          out.write("            'sidebar-mini': oneui.settings.sidebarMini,\r\n");
          out.write("            'side-overlay-o': oneui.settings.sideOverlayOpen,\r\n");
          out.write("            'side-overlay-hover': oneui.settings.sideOverlayHover,\r\n");
          out.write("            'side-scroll': oneui.settings.sideScroll,\r\n");
          out.write("            'header-navbar-fixed': oneui.settings.headerFixed\r\n");
          out.write("        }\" style=\"height: 100%; overflow:hidden;\">\r\n");
          out.write("            <!-- Side Overlay-->\r\n");
          out.write("            <aside data-ng-include=\"'assets/views/partials/base_side_overlay.html'\" data-ng-controller=\"SideOverlayCtrl\" id=\"side-overlay\"></aside>\r\n");
          out.write("\r\n");
          out.write("            <!-- Sidebar -->\r\n");
          out.write("            ");
          out.write("\r\n");
          out.write("                ");
          out.write("\r\n");
          out.write("            ");
          out.write("\r\n");
          out.write("            <nav data-ng-controller=\"SidebarCtrl\" id=\"sidebar\" style=\"overflow: visible;\">\r\n");
          out.write("                ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
          out.write("\r\n");
          out.write("            </nav>\r\n");
          out.write("\r\n");
          out.write("            <!-- Header -->\r\n");
          out.write("            ");
if(headUrl!=null&&!"".equals(headUrl)){
          out.write("\r\n");
          out.write("                ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, headUrl, out, false);
          out.write("\r\n");
          out.write("            ");
}
          out.write("\r\n");
          out.write("\r\n");
          out.write("            <!-- Main Container -->\r\n");
          out.write("            <!--<main id=\"main-container\" data-autoscroll=\"true\" data-ui-view  ></main>-->\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("            <!--<uib-tabset active=\"activeForm\"  >-->\r\n");
          out.write("                <!--<uib-tab index=\"0\" heading=\"Form Tab\">-->\r\n");
          out.write("                  <!--<div data-ng-include=\"'assets/views/tables_datatables1.html'\" >  </div>-->\r\n");
          out.write("                <!--</uib-tab>-->\r\n");
          out.write("                <!--<uib-tab index=\"1\" heading=\"Tab One\">-->\r\n");
          out.write("                    <!--1 Tab Content-->\r\n");
          out.write("                    <!--<div class=\"form-group\"  data-ui-view=\"tab1View\" >  </div>-->\r\n");
          out.write("                <!--</uib-tab>-->\r\n");
          out.write("                <!--<uib-tab index=\"2\" heading=\"Tab Two\">-->\r\n");
          out.write("                    <!--2 Tab Content-->\r\n");
          out.write("                    <!--<div class=\"form-group\"  data-ui-view=\"tab2View\" >  </div>-->\r\n");
          out.write("                <!--</uib-tab>-->\r\n");
          out.write("            <!--</uib-tabset>-->\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("            <!--<a href=\"#\" data-ng-click=\"addTab('AAAAA','assets/views/tables_datatables1.html')\"> addTab</a>-->\r\n");
          out.write("            <!--<a href=\"#\" data-ng-click=\"removeTab(1)\"> removeTab</a>-->\r\n");
          out.write("            <!--<md-tabs md-selected=\"selectedIndex\" md-border-bottom md-autoselect>-->\r\n");
          out.write("                <!--<md-tab ng-repeat=\"tab in tabs\"  ng-disabled=\"tab.disabled\"  label=\"{{tab.title}}\">-->\r\n");
          out.write("                    <!--<div data-ng-include=\"'{{tab.content}}'\" >sss </div>-->\r\n");
          out.write("                <!--</md-tab>-->\r\n");
          out.write("            <!--</md-tabs>     -->\r\n");
          out.write("            <uib-tabset  active=\"mainTab.tabActiveId\" id=\"main-container\" style=\"height: 100%; overflow:hidden;  position: relative; \"  class=\"mainTab\" >\r\n");
          out.write("                <uib-tab  data-ng-repeat=\"tab in mainTab.tabs\"  index=\"tab.id\"   style=\"height: 100%;\"  heading=\"{{tab.title}}\">\r\n");
          out.write("                    <uib-tab-heading>\r\n");
          out.write("                        <i class=\"fa fa-times\"  style=\"cursor:pointer;\" title=\"close\" ng-show=\"tab.closeable\"  ng-click =\"mainTab.removeTab(tab);\" ></i>\r\n");
          out.write("                        ");
          out.write("\r\n");
          out.write("                        {{tab.title}}\r\n");
          out.write("                    </uib-tab-heading>\r\n");
          out.write("                    <!--<div ng-include=\"tab.content\" style=\"height: 100%;\"  class=\"mainTabContent\"   data-js-slimscroll=\"{ alwaysVisible: true, height: '100%' , railOpacity: '.55', size: '6px'}\">  </div>-->\r\n");
          out.write("                    <!--<div ng-include=\"tab.content\" style=\"height: 100%; overflow-x: hidden; overflow-y: auto;\"  class=\"mainTabContent \"    du-scroll-container   >  </div>-->\r\n");
          out.write("                    <!--等待-->\r\n");
          out.write("                    <div class=\"wait-main\"  style=\"position: relative; height: 100%; width: 100%; \" >\r\n");
          out.write("                        <div class=\"wait-div\" style=\" position: absolute;text-align:center; display: none; top: 0; right: 0; bottom: 0;  left: 0; z-index: 2999; width:100%;height: 100%;box-sizing: border-box; \" >\r\n");
          out.write("                            <i class=\"fa fa-3x fa-sun-o fa-spin text-primary\" style=\" position: absolute;left:50% ;top:50%\"></i>\r\n");
          out.write("                        </div>\r\n");
          out.write("                        <div    ng-if=\"tab.iframeFlag == false\"  ng-include=\"tab.content\" style=\"height: 100%; /*overflow-x: hidden; overflow-y: auto;*/\"  class=\"mainTabContent \" >\r\n");
          out.write("\r\n");
          out.write("                        </div>\r\n");
          out.write("\r\n");
          out.write("                        <iframe  ng-if=\"tab.iframeFlag == true\" ngf-src=\"tab.content\" width=\"100%\" height=\"100%\" style=\"height: 100%; width: 100%; border: 0px; overflow-x: hidden; overflow-y: auto;\" frameborder=\"0\"   class=\"mainTabContent \" >\r\n");
          out.write("\r\n");
          out.write("                        </iframe>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </uib-tab>\r\n");
          out.write("            </uib-tabset>\r\n");
          out.write("\r\n");
          out.write("            <!-- Footer -->\r\n");
          out.write("            <!--<footer data-ng-include=\"'assets/views/partials/base_footer.html'\" id=\"page-footer\" class=\"content-mini content-mini-full font-s12 bg-gray-lighter clearfix\"></footer>-->\r\n");
          out.write("        </div>\r\n");
          out.write("        <!-- END Page Container -->\r\n");
          out.write("\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_e_005fmainPage_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_e_005fmainPage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fe_005fmainPage_0026_005floading.reuse(_jspx_th_e_005fmainPage_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fe_005fmainPage_0026_005floading.reuse(_jspx_th_e_005fmainPage_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"");
      out.print(root+welcomeJs);
      out.write("?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("         ");
      out.write("  \r\n");
      out.write("<script src=\"resources/js/extendjs.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    .edui-default .edui-dialog {\r\n");
      out.write("        z-index:19999;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("    window.UEDITOR_HOME_URL =  root+\"/frame/component/ueditor/\";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"resources/js/ueditor_config.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"frame/component/ueditor/ueditor_all.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"frame/component/ueditor/uparse.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
