/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JBoss EAP 7.1.0.GA (WildFly Core 3.0.10.Final-redhat-1) - 1.4.18.Final-redhat-2
 * Generated at: 2021-03-24 02:32:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.website.canbaodengji;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class canbaodengjiDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .enlarge img{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: all 0.6s;\r\n");
      out.write("        -ms-transition: all 0.8s;\r\n");
      out.write("    }\r\n");
      out.write("    .enlarge img:hover{\r\n");
      out.write("        transform: scale(1.2);\r\n");
      out.write("        -ms-transform: scale(1.2);\r\n");
      out.write("    }\r\n");
      out.write("    .mytoolbar{\r\n");
      out.write("\r\n");
      out.write("        background:#e6f5fe;\r\n");
      out.write("    }\r\n");
      out.write("    .myhead{\r\n");
      out.write("        background: #e6f5fe;\r\n");
      out.write("        color:#1ea6fc;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        line-height: 28px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .myicon{\r\n");
      out.write("        padding-right: 6px;\r\n");
      out.write("    }\r\n");
      out.write("    .content p, .content .push, .content .block, .content .items-push > div{\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .block-title{\r\n");
      out.write("        font-size:17px;\r\n");
      out.write("        color:#5c90d2;\r\n");
      out.write("        line-height:36px;\r\n");
      out.write("    }\r\n");
      out.write("    label{\r\n");
      out.write("        color:#7789a2;\r\n");
      out.write("        font-size:14px;\r\n");
      out.write("    }\r\n");
      out.write("    .detail-content>div{\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        width: 50%;\r\n");
      out.write("        /*text-align: center;*/\r\n");
      out.write("    }\r\n");
      out.write("    .detail-content img{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 250px;\r\n");
      out.write("    }\r\n");
      out.write("    .detail-content>div:first-child{\r\n");
      out.write("        border-right: 1px solid #999;\r\n");
      out.write("    }\r\n");
      out.write("    .img-wrapper{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("    }\r\n");
      out.write("    .img-wrapper>img{\r\n");
      out.write("        margin-top: 6px;\r\n");
      out.write("        width: 23%;\r\n");
      out.write("        border: solid 1px red;\r\n");
      out.write("        height: 250px;\r\n");
      out.write("        margin-right: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mes-dets div:first-child {\r\n");
      out.write("        color: #999;\r\n");
      out.write("        width: 74px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mes-dets div:nth-child(2) {\r\n");
      out.write("        -webkit-box-flex: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .information_list span:first-child {\r\n");
      out.write("        color: #8B99AC;\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("    .select-wrap label{\r\n");
      out.write("        width: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    .select-wrap .k-dropdown-wrap.k-state-default{\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        border:none;\r\n");
      out.write("        cursor: default;\r\n");
      out.write("    }\r\n");
      out.write("    .select-wrap .k-state-default>.k-select{\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("    .select-wrap .k-dropdown-wrap.k-state-default.k-state-focused{\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border: none;\r\n");
      out.write("        box-shadow: none;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<div style=\"width:100%; height:100%;  overflow-y: auto;\" data-ng-controller=\"canbaodengjiDetailCtrl\"\r\n");
      out.write("     kendo-validator=\"Validator\">\r\n");
      out.write("    ");
      if (_jspx_meth_e_005fhidden_005f0(_jspx_page_context))
        return;
      out.write("  <!--审批ID-->\r\n");
      out.write("    ");
      if (_jspx_meth_e_005fhidden_005f1(_jspx_page_context))
        return;
      out.write("  <!--审批-->\r\n");
      out.write("    ");
      if (_jspx_meth_e_005fhidden_005f2(_jspx_page_context))
        return;
      out.write("  <!--审批-->\r\n");
      out.write("    ");
      if (_jspx_meth_e_005fhidden_005f3(_jspx_page_context))
        return;
      out.write("  <!--审批-->\r\n");
      out.write("    ");
      if (_jspx_meth_e_005fhidden_005f4(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_e_005fhidden_005f5(_jspx_page_context))
        return;
      out.write("  <!--审批-->\r\n");
      out.write("\r\n");
      out.write("    <div style=\"width:100%;height:100%; height:calc(100% - 10px);position: relative; \">\r\n");
      out.write("        <div class=\"toolbar mytoolbar\" style=\"height:45px;\">\r\n");
      out.write("            <div class=\"myhead\">\r\n");
      out.write("                <div style=\"float: left\">\r\n");
      out.write("                    <span class=\"block-title\"><i class=\"fa fa-file-o \"></i> 居民医疗参保登记申请 </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"pull-right\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                    <div class=\" btn-group\" ng-show=\"form.aac019=='0'\">\r\n");
      out.write("                        <button class=\"btn btn-primary\" type=\"button\" data-toggle=\"tooltip\" title=\"通过\"\r\n");
      out.write("                                ng-click=\"saveTriage(2)\"><i class=\"glyphicon glyphicon-paperclip\"></i> 通过\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\" btn-group\" ng-show=\"form.aac019=='0'\">\r\n");
      out.write("                        <button class=\"btn btn-danger\" type=\"button\" data-toggle=\"tooltip\" title=\"不通过\"\r\n");
      out.write("                                ng-click=\"saveTriage(1)\"><i class=\"fa fa-remove\"></i> 不通过\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content content-narrow\" style=\"width:100%; height:calc(100% - 40px); overflow-y: auto;  \">\r\n");
      out.write("            <div class=\"block\">\r\n");
      out.write("                <div class=\"block-header\">\r\n");
      out.write("                    <div class=\"block-options-simple block-options-simple-left\">\r\n");
      out.write("                        <span class=\"block-title \"><i class=\"fa fa-building myicon\"></i>审批信息</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"block-content \">\r\n");
      out.write("                    <div class=\"row form-group\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_e_005fhidden_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_e_005fhidden_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <div class=\"col-xs-4\">\r\n");
      out.write("        <div class=\"information_list\">\r\n");
      out.write("            <span>申请日期</span>\r\n");
      out.write("            <span>{{form.aac016}}</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-xs-4\">\r\n");
      out.write("        <div class=\"information_list\">\r\n");
      out.write("            <span>审批日期</span>\r\n");
      out.write("            <span>{{form.aac022}}</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div ng-show=\"form.aac019 == '0'\" style=\"display: flex;justify-content: flex-end;\">\r\n");
      out.write("        <span style=\"color: orange ;font-weight: bold;font-size: 18px;margin-right: 20px;border: solid orange 1px;border-radius: 16px;padding: 2px 16px\">待审批</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div ng-show=\"form.aac019 == '2'\" style=\"display: flex;justify-content: flex-end;\">\r\n");
      out.write("        <span style=\"color: green ;font-weight: bold;font-size: 18px;margin-right: 20px;border: solid green 1px;border-radius: 16px;padding: 2px 10px\">登记已完成</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div ng-show=\"form.aac019 == '1'\" style=\"display: flex;justify-content: flex-end;\">\r\n");
      out.write("        <span style=\"color: red ;font-weight: bold;font-size: 18px;margin-right: 20px;border: solid red 1px;border-radius: 16px;padding: 2px 10px\">登记不通过</span>\r\n");
      out.write("    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            ");
      if (_jspx_meth_e_005ftextarea_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"block\">\r\n");
      out.write("                <div class=\"block-header\">\r\n");
      out.write("                    <div class=\"block-options-simple block-options-simple-left\">\r\n");
      out.write("                        <span class=\"block-title \"><i class=\"fa fa-building myicon\"></i>基本信息</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
      if (_jspx_meth_e_005fhidden_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_e_005fhidden_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_e_005fhidden_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_e_005fhidden_005f11(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_e_005fhidden_005f12(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_e_005fhidden_005f13(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_e_005fhidden_005f14(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <div class=\"block-content \">\r\n");
      out.write("                    <div class=\"row form-group\">\r\n");
      out.write("                        <div class=\"col-xs-12\">\r\n");
      out.write("                            <div class=\"information_list\">\r\n");
      out.write("                                <span>业务单号</span>\r\n");
      out.write("                                <span>{{form.aar014}}</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row form-group\">\r\n");
      out.write("                        <div class=\"col-xs-6 select-wrap\" style=\"display: flex\">\r\n");
      out.write("                            ");
      if (_jspx_meth_e_005fselect_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-6 select-wrap\" style=\"display: flex\">\r\n");
      out.write("                            ");
      if (_jspx_meth_e_005fselect_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row form-group\">\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                            <div class=\"information_list\">\r\n");
      out.write("                                <span>办理人姓名</span>\r\n");
      out.write("                                <span>{{form.aac003}}</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                            <div class=\"information_list\">\r\n");
      out.write("                                <span>办理人身份证</span>\r\n");
      out.write("                                <span>{{form.aac147}}</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row form-group\">\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                            <div class=\"information_list\">\r\n");
      out.write("                                <span>参保年度</span>\r\n");
      out.write("                                <span>{{form.aac148}}</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                            <div class=\"information_list\">\r\n");
      out.write("                                <span>联系电话</span>\r\n");
      out.write("                                <span>{{form.aac014}}</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row form-group\">\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                            <div class=\"information_list\">\r\n");
      out.write("                                <span>所属区镇</span>\r\n");
      out.write("                                <span>{{form.aac009}}</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                            <div class=\"information_list\">\r\n");
      out.write("                                <span>所属社区</span>\r\n");
      out.write("                                <span>{{form.aac010}}</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
      if (_jspx_meth_e_005fhidden_005f15(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <div class=\"block \" ng-show=\"form.aac007=='0' || form.aac007=='1'\">\r\n");
      out.write("                <div class=\"block-header\">\r\n");
      out.write("                    <div class=\"block-options-simple block-options-simple-left\">\r\n");
      out.write("                        <span class=\"block-title \"><i class=\"fa fa-thumb-tack myicon\"></i>居民医疗参保登记申请材料</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\" style=\"color: #7789a2;font-size: 14px;padding: 15px\">\r\n");
      out.write("                    <span>参保人员户口本首页</span>\r\n");
      out.write("                    <div class=\"img-wrapper\">\r\n");
      out.write("                        <div ng-repeat=\"ar10DTO in form.list1\" class=\"col-xs-4\">\r\n");
      out.write("                            <img style=\"width: 250px;height: 250px; cursor: pointer;\" src=\"{{ar10DTO.zpUrl}}\" ng-click=\"showImg(ar10DTO);\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\" style=\"color: #7789a2;font-size: 14px;padding: 15px\">\r\n");
      out.write("                    <span>参保人员户口本主页</span>\r\n");
      out.write("                    <div class=\"img-wrapper\">\r\n");
      out.write("                        <div ng-repeat=\"ar10DTO in form.list2\" class=\"col-xs-4\">\r\n");
      out.write("                            <img style=\"width: 250px;height: 250px; cursor: pointer;\" src=\"{{ar10DTO.zpUrl}}\" ng-click=\"showImg(ar10DTO);\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\" style=\"color: #7789a2;font-size: 14px;padding: 15px\">\r\n");
      out.write("                    <span>参保人员户口本参保人页</span>\r\n");
      out.write("                    <div class=\"img-wrapper\">\r\n");
      out.write("                        <div ng-repeat=\"ar10DTO in form.list22\" class=\"col-xs-4\">\r\n");
      out.write("                            <img style=\"width: 250px;height: 250px; cursor: pointer;\" src=\"{{ar10DTO.zpUrl}}\" ng-click=\"showImg(ar10DTO);\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\" style=\"color: #7789a2;font-size: 14px;padding: 15px\" ng-show=\"form.aac008 != '1'\">\r\n");
      out.write("                    <span>其他相关证明材料</span>\r\n");
      out.write("                    <div class=\"img-wrapper\">\r\n");
      out.write("                        <div ng-repeat=\"ar10DTO in form.list9\" class=\"col-xs-4\">\r\n");
      out.write("                            <img style=\"width: 250px;height: 250px; cursor: pointer;\" src=\"{{ar10DTO.zpUrl}}\" ng-click=\"showImg(ar10DTO);\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_e_005fhidden_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f0 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f0);
    _jspx_th_e_005fhidden_005f0.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(101,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f0.setName("aar014");
    _jspx_th_e_005fhidden_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f0);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f1 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f1);
    _jspx_th_e_005fhidden_005f1.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(102,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f1.setName("aac019");
    _jspx_th_e_005fhidden_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f1);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f2 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f2);
    _jspx_th_e_005fhidden_005f2.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(103,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f2.setName("aac007");
    _jspx_th_e_005fhidden_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f2);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f3 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f3);
    _jspx_th_e_005fhidden_005f3.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(104,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f3.setName("aac018");
    _jspx_th_e_005fhidden_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f3);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f4 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f4);
    _jspx_th_e_005fhidden_005f4.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(105,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f4.setName("openId");
    _jspx_th_e_005fhidden_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f4);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f5 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f5);
    _jspx_th_e_005fhidden_005f5.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(107,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f5.setName("aac023");
    _jspx_th_e_005fhidden_005f5.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f5);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f6 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f6);
    _jspx_th_e_005fhidden_005f6.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(152,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f6.setName("aac016");
    _jspx_th_e_005fhidden_005f6.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f6);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f7 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f7);
    _jspx_th_e_005fhidden_005f7.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(153,4) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f7.setName("aac022");
    _jspx_th_e_005fhidden_005f7.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f7);
    return false;
  }

  private boolean _jspx_meth_e_005ftextarea_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:textarea
    com.eframework.web.tags.TextAreaTag _jspx_th_e_005ftextarea_005f0 = (new com.eframework.web.tags.TextAreaTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005ftextarea_005f0);
    _jspx_th_e_005ftextarea_005f0.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(188,28) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005ftextarea_005f0.setName("aac020");
    // /website/canbaodengji/canbaodengjiDetail.jsp(188,28) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005ftextarea_005f0.setLabel("审批意见");
    _jspx_th_e_005ftextarea_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005ftextarea_005f0);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f8 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f8);
    _jspx_th_e_005fhidden_005f8.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(199,16) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f8.setName("aar014");
    _jspx_th_e_005fhidden_005f8.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f8);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f9 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f9);
    _jspx_th_e_005fhidden_005f9.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(200,16) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f9.setName("aac003");
    _jspx_th_e_005fhidden_005f9.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f9);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f10 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f10);
    _jspx_th_e_005fhidden_005f10.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(201,16) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f10.setName("aac147");
    _jspx_th_e_005fhidden_005f10.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f10);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f11 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f11);
    _jspx_th_e_005fhidden_005f11.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(202,16) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f11.setName("aac148");
    _jspx_th_e_005fhidden_005f11.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f11);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f12 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f12);
    _jspx_th_e_005fhidden_005f12.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(203,16) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f12.setName("aac014");
    _jspx_th_e_005fhidden_005f12.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f12);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f13 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f13);
    _jspx_th_e_005fhidden_005f13.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(204,16) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f13.setName("aac009");
    _jspx_th_e_005fhidden_005f13.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f13);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f14 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f14);
    _jspx_th_e_005fhidden_005f14.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(205,16) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f14.setName("aac010");
    _jspx_th_e_005fhidden_005f14.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f14);
    return false;
  }

  private boolean _jspx_meth_e_005fselect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:select
    com.eframework.web.tags.SelectFieldTag _jspx_th_e_005fselect_005f0 = (new com.eframework.web.tags.SelectFieldTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fselect_005f0);
    _jspx_th_e_005fselect_005f0.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(217,28) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fselect_005f0.setName("aac007");
    // /website/canbaodengji/canbaodengjiDetail.jsp(217,28) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fselect_005f0.setLabel("业务类型");
    // /website/canbaodengji/canbaodengjiDetail.jsp(217,28) name = readonly type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fselect_005f0.setReadonly("true");
    // /website/canbaodengji/canbaodengjiDetail.jsp(217,28) name = dictionaryNo type = java.lang.String reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fselect_005f0.setDictionaryNo("DIC_JMYBDJ_YWLX");
    _jspx_th_e_005fselect_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fselect_005f0);
    return false;
  }

  private boolean _jspx_meth_e_005fselect_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:select
    com.eframework.web.tags.SelectFieldTag _jspx_th_e_005fselect_005f1 = (new com.eframework.web.tags.SelectFieldTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fselect_005f1);
    _jspx_th_e_005fselect_005f1.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(220,28) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fselect_005f1.setName("aac008");
    // /website/canbaodengji/canbaodengjiDetail.jsp(220,28) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fselect_005f1.setLabel("人员类别");
    // /website/canbaodengji/canbaodengjiDetail.jsp(220,28) name = readonly type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fselect_005f1.setReadonly("true");
    // /website/canbaodengji/canbaodengjiDetail.jsp(220,28) name = dictionaryNo type = java.lang.String reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fselect_005f1.setDictionaryNo("DIC_JMYBDJ_RYLB");
    _jspx_th_e_005fselect_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fselect_005f1);
    return false;
  }

  private boolean _jspx_meth_e_005fhidden_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f15 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f15);
    _jspx_th_e_005fhidden_005f15.setJspContext(_jspx_page_context);
    // /website/canbaodengji/canbaodengjiDetail.jsp(306,12) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f15.setName("ar10DTOArrayListJson");
    _jspx_th_e_005fhidden_005f15.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f15);
    return false;
  }
}
