/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JBoss EAP 7.1.0.GA (WildFly Core 3.0.10.Final-redhat-1) - 1.4.18.Final-redhat-2
 * Generated at: 2021-03-24 01:17:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.website.show;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.eframework.module.comp.login.LoginThreadLocal;

public final class mainhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.eframework.module.comp.login.LoginThreadLocal");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String root = request.getContextPath();
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .white-block {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .white-block-header{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 0 20px;\r\n");
      out.write("        border-bottom: 1px solid #EDEDED;\r\n");
      out.write("        height: 52px;\r\n");
      out.write("    }\r\n");
      out.write("    .menu-icon-wrapper{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        height: 80px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .menus-wrap{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        padding: 1px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .menu{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        border-right: 1px solid #ededed;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        margin: 12px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .menu>div:nth-child(2){\r\n");
      out.write("        margin-left: 18px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .menu>div:nth-child(2)>div:first-child{\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .menu>div:nth-child(2)>div:last-child{\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: #999999;\r\n");
      out.write("    }\r\n");
      out.write("    .menu:last-child{\r\n");
      out.write("        border-right: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .textFont {\r\n");
      out.write("        width: 154px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<div style=\"width:100%; height:100%;overflow-y: hidden\" data-ng-controller=\"MainHomeCtrl\"   kendo-validator=\"validator\">\r\n");
      out.write("    <div class=\"tabpanel\" style=\"width:100%;height:100%;  min-width: 734px;\">\r\n");
      out.write("        <div class=\"tab-content\" style=\" height: 100%;background: #f5F5F5;padding:15px 0 20px;overflow: scroll\">\r\n");
      out.write("            <div class=\"white-block\">\r\n");
      out.write("                <div class=\"white-block-header\">\r\n");
      out.write("                    <img width=\"19\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/xinwen.png\" alt=\"\">\r\n");
      out.write("                    <div style=\"margin-left: 10px\">\r\n");
      out.write("                        <span style=\"font-size: 18px;font-weight: 600;\">新闻维护</span>\r\n");
      out.write("                        <span style=\"font-size: 12px \">/ News Maintenance</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"white-block-content\">\r\n");
      out.write("                    <div class=\"menus-wrap\">\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openLanMu()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #24C1C9;\">\r\n");
      out.write("                                <img width=\"39\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/lanmu.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>栏目管理</div>\r\n");
      out.write("                                <div class=\"textFont\">新闻栏目维护</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openXinWen()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #FACA00;\">\r\n");
      out.write("                                <img width=\"48\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/shangchuan.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>新闻上传</div>\r\n");
      out.write("                                <div class=\"textFont\">上传将要发布的新闻素材</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openShenHe()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #AA7DF6;\">\r\n");
      out.write("                                <img width=\"43\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/fabu.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>审核发布</div>\r\n");
      out.write("                                <div class=\"textFont\">审核上传的新闻内容</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"white-block\">\r\n");
      out.write("                <div class=\"white-block-header\">\r\n");
      out.write("                    <img width=\"19\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/yewu.png\" alt=\"\">\r\n");
      out.write("                    <div style=\"margin-left: 10px\">\r\n");
      out.write("                        <span style=\"font-size: 18px;font-weight: 600;\">业务经办</span>\r\n");
      out.write("                        <span style=\"font-size: 12px \">/ Business Handling</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"white-block-content\">\r\n");
      out.write("                    <div class=\"menus-wrap\">\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openLingXing()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #91D032;\">\r\n");
      out.write("                                <img width=\"37\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/baoxiao.png\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>零星报销</div>\r\n");
      out.write("                                <div class=\"textFont\">处理零星报销业务</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openShengYu()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #FF8F28;\">\r\n");
      out.write("                                <img width=\"36\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/fabu.png\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>生育报销</div>\r\n");
      out.write("                                <div class=\"textFont\">处理生育报销业务</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openYiDi()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #39C7CE;\">\r\n");
      out.write("                                <img width=\"42\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/beian.png\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>异地备案</div>\r\n");
      out.write("                                <div class=\"textFont\">处理异地备案业务</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openJuMinCanBao()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #FACF19;\">\r\n");
      out.write("                                <img width=\"34\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/zhuanru.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>居民参保</div>\r\n");
      out.write("                                <div class=\"textFont\">处理居民参保登记业务</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openJuMinCanBaoBianGeng()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #B28AF7;\">\r\n");
      out.write("                                <img width=\"34\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/zhuanchu.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>参保变更</div>\r\n");
      out.write("                                <div class=\"textFont\">处理居民医保变更登记业务</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"white-block\">\r\n");
      out.write("                <div class=\"white-block-header\">\r\n");
      out.write("                    <img width=\"19\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/xinwen.png\" alt=\"\">\r\n");
      out.write("                    <div style=\"margin-left: 10px\">\r\n");
      out.write("                        <span style=\"font-size: 18px;font-weight: 600;\">业务经办</span>\r\n");
      out.write("                        <span style=\"font-size: 12px \">/ Business Handling</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"white-block-content\">\r\n");
      out.write("                    <div class=\"menus-wrap\">\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openTeBing()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #B28AF7;\">\r\n");
      out.write("                                <img width=\"38\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/tongji-item.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>门诊特病</div>\r\n");
      out.write("                                <div class=\"textFont\">处理门诊特病申请业务</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"white-block\">\r\n");
      out.write("                <div class=\"white-block-header\">\r\n");
      out.write("                    <img width=\"18\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/weihu.png\" alt=\"\">\r\n");
      out.write("                    <div style=\"margin-left: 10px\">\r\n");
      out.write("                        <span style=\"font-size: 18px;font-weight: 600;\">基础维护</span>\r\n");
      out.write("                        <span style=\"font-size: 12px \">/ Basic Maintenance</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"white-block-content\">\r\n");
      out.write("                    <div class=\"menus-wrap\">\r\n");
      out.write("                        <div class=\"menu\" ng-click=\"openJuZhen()\">\r\n");
      out.write("                            <div class=\"menu-icon-wrapper\" style=\"background: #FAD430;\">\r\n");
      out.write("                                <img width=\"38\" src=\"");
      out.print(root);
      out.write("/website/show/img/shouye/juzhentu.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div>微信矩阵</div>\r\n");
      out.write("                                <div class=\"textFont\">维护医保相关微信公众号</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
