/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JBoss EAP 7.1.0.GA (WildFly Core 3.0.10.Final-redhat-1) - 1.4.18.Final-redhat-2
 * Generated at: 2021-03-24 01:16:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.website.show;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.eframework.core.config.systemconfig.SystemConfig;
import com.eframework.core.xml.config.systemconfig.SystemConfigXML;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.eframework.core.config.systemconfig.SystemConfig");
    _jspx_imports_classes.add("com.eframework.core.xml.config.systemconfig.SystemConfigXML");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String root = request.getContextPath();
    String jsVersion= SystemConfig.getConfigXML().getJsVersion();
    String yzcodenum = (String)request.getSession().getAttribute(com.google.code.kaptcha.Constants.KAPTCHA_SESSION_KEY);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 9]>         <html class=\"ie9 no-focus\" data-ng-app=\"app\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 9]><!--> <html class=\"no-focus\" data-ng-app=\"app\" lang=\"en\"> <!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("    <title>用户登录</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"description\" content=\"OneUI - Admin Dashboard Template &amp; UI Framework created by pixelcave and published on Themeforest\">\r\n");
      out.write("    <meta name=\"author\" content=\"pixelcave\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex, nofollow\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icons -->\r\n");
      out.write("    <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/favicon-16x16.png\" sizes=\"16x16\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/favicon-32x32.png\" sizes=\"32x32\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/favicon-96x96.png\" sizes=\"96x96\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/favicon-160x160.png\" sizes=\"160x160\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/favicon-192x192.png\" sizes=\"192x192\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"");
      out.print(root);
      out.write("/assets/img/favicons/apple-touch-icon-180x180.png\">\r\n");
      out.write("    <!-- END Icons -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Stylesheets -->\r\n");
      out.write("    <!-- Page JS Plugins CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root);
      out.write("/assets/js/plugins/magnific-popup/magnific-popup.min.css?jsVersion=");
      out.print(jsVersion);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap and OneUI CSS framework -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root);
      out.write("/website/show/resource/css/compatible.css?jsVersion=");
      out.print(jsVersion);
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root);
      out.write("/assets/css/bootstrap.min.css?jsVersion=");
      out.print(jsVersion);
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" id=\"css-main\" href=\"");
      out.print(root);
      out.write("/assets/css/oneui.css?jsVersion=");
      out.print(jsVersion);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("    <!-- You can include a specific file from css/themes/ folder to alter the default color theme of the template. eg: -->\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" id=\"css-theme\" href=\"");
      out.print(root);
      out.write("/assets/css/themes/flat.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root);
      out.write("/assets/js/plugins/slick/slick.min.css?jsVersion=");
      out.print(jsVersion);
      out.write("\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(root);
      out.write("/assets/js/plugins/slick/slick-theme.min.css?jsVersion=");
      out.print(jsVersion);
      out.write("\">\r\n");
      out.write("    <link href=\"");
      out.print(root);
      out.write("/assets/css/kendo/kendo.common.min.css?jsVersion=");
      out.print(jsVersion);
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(root);
      out.write("/assets/css/kendo/kendo.rtl.min.css?jsVersion=");
      out.print(jsVersion);
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(root);
      out.write("/assets/css/kendo/kendo.silver.min.css?jsVersion=");
      out.print(jsVersion);
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(root);
      out.write("/assets/css/kendo/kendo.silver.mobile.min.css?jsVersion=");
      out.print(jsVersion);
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"   href=\"");
      out.print(root);
      out.write("/frame/resource/css/ext-kendo.css?jsVersion=");
      out.print(jsVersion);
      out.write("\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <script >\r\n");
      out.write("        var root = \"");
      out.print(root);
      out.write("\";\r\n");
      out.write("        var frameControlUserId=\"\";\r\n");
      out.write("        var frameCrypto=\"\";\r\n");
      out.write("        //格式化URL\r\n");
      out.write("        function formatURL(url) {\r\n");
      out.write("            if (url.indexOf(\"http:\") == 0 || url.indexOf(\"https:\") == 0) {\r\n");
      out.write("\r\n");
      out.write("            }else if (url.indexOf(\"//\") == 0 ) {\r\n");
      out.write("                url=str.substring(1);\r\n");
      out.write("            } else {\r\n");
      out.write("                if (url.indexOf(\"/\") == 0) {\r\n");
      out.write("                    url = root + url;\r\n");
      out.write("                } else {\r\n");
      out.write("                    url = root + \"/\" + url;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            return url;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- END Stylesheets -->\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("   html,body{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size:12px;\r\n");
      out.write("        color:#464646;\r\n");
      out.write("        font-family:Arial, Helvetica, sans-serif;\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .top{\r\n");
      out.write("        height:200px;\r\n");
      out.write("    }\r\n");
      out.write("    .logo{\r\n");
      out.write("        padding-top:100px;\r\n");
      out.write("        padding-left:600px;\r\n");
      out.write("    }\r\n");
      out.write("    .left{\r\n");
      out.write("        float:left;\r\n");
      out.write("\r\n");
      out.write("        width:50%;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .login{\r\n");
      out.write("        float:left;\r\n");
      out.write("        min-width:300px;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        height:290px;\r\n");
      out.write("        align:center;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("        background-color:#FFFFFF;\r\n");
      out.write("        border:10px solid #ECF7FB ;\r\n");
      out.write("        box-shadow: 0 12px 5px #D8D8D8;\r\n");
      out.write("        border-radius:20px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .right{\r\n");
      out.write("        float:left;\r\n");
      out.write("        min-width:300px;\r\n");
      out.write("        width:26%;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .footer{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        height:100px;\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        background: url(");
      out.print(root);
      out.write("/website/show/img/footer.png);\r\n");
      out.write("        background-repeat:repeat-x;\r\n");
      out.write("        position:fixed;\r\n");
      out.write("        bottom:0;\r\n");
      out.write("        left:0;\r\n");
      out.write("        width:100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    input {\r\n");
      out.write("        -webkit-appearance: textfield;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        -webkit-rtl-ordering: logical;\r\n");
      out.write("        user-select: text;\r\n");
      out.write("        cursor: auto;\r\n");
      out.write("        padding: 1px;\r\n");
      out.write("        border: 1px solid #5d99c1bd;\r\n");
      out.write("        border-width: 1px;\r\n");
      out.write("        border-style: solid;\r\n");
      out.write("        border-color: deepskyblue;\r\n");
      out.write("        border-image: initial;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"checkbox\"] {\r\n");
      out.write("        margin: 3px 3px 3px 4px;\r\n");
      out.write("        -webkit-appearance: checkbox;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body  data-ng-controller=\"UserLoginCtrl\" >\r\n");
      if (_jspx_meth_e_005fhidden_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- Lock Screen Content -->\r\n");
      out.write("<table width=\"100%\"  height=\"100%\" style=\"width: 100%; \">\r\n");
      out.write("    <tr   style=\"height:200px;\">\r\n");
      out.write("        <td style=\"width: 100%;\" >\r\n");
      out.write("            <div style=\"width:100%;height:200px;position: fixed;top:0;\">\r\n");
      out.write("                <img src=\"");
      out.print(root);
      out.write("/website/show/img/hometop.png\" style=\"width:100%; height:200px;\"/>\r\n");
      out.write("                <div style=\"position: fixed;top:100px;right:18%;\">\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <h1 class=\"font-s48 font-w700 text-uppercase text-primary text-center animated fadeInDown\" data-toggle=\"appear\" data-class=\"animated fadeInDown\">昆山医保微信号-综合管理平台</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr  style=\"height:300px;\" >\r\n");
      out.write("        <td style=\"width: 100%;\" >\r\n");
      out.write("        <table width:100%;style=\"width: 100%;margin:auto;\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td width=\"50%\"  style=\"width:50%;\">\r\n");
      out.write("                    <img src=\"");
      out.print(root);
      out.write("/website/show/img/homeleft.png\" style=\"width:100%;height:300px;\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td width=\"30%\" style=\"align:center; text-align:center;  width:30%;height:200px;background:url(");
      out.print(root);
      out.write("/website/show/img/homeindex.png) repeat-x;\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"login\" style=\"width:95%;margin: auto;\">\r\n");
      out.write("                        <div style=\"text-align:center !important; font-size:20px;margin-top:20px;margin-bottom:15px; color:#5A8ED1;font-weight: bold\">登&nbsp;&nbsp;录</div>\r\n");
      out.write("                        <div><input ng-model=\"form.userId\"  placeholder=\"请输入账号/用户名\" type=\"text\"style=\"padding-left:5px;margin:0 auto;margin-bottom:15px;width:74%;height:25px;border:1px solid #5d99c1bd;border-radius:5px;color:#000000;\"></div>\r\n");
      out.write("                        <div><input ng-model=\"form.password\" placeholder=\"请输入密码\" type=\"password\" style=\"padding-left:5px;margin:0 auto;margin-bottom:15px;width:74%;;height:25px;border:1px solid #5d99c1bd;border-radius:5px;color:#000000;\"></div>\r\n");
      out.write("                        <div style=\"text-align: left;\">\r\n");
      out.write("                            <input ng-model=\"form.key\" placeholder=\"请输入验证码\" type=\"text\" style=\"padding-left:5px;margin-left:13%;margin-bottom:15px;width:30%;;height:25px;border:1px solid #5d99c1bd;border-radius:5px;color:#000000;\">\r\n");
      out.write("                            <img style=\"width: 35%;height: 25px;margin-left: 8%;\" id=\"kaptchaImage\" src=\"/web/kaptcha.jpg\" onclick=\"$('#kaptchaImage').attr('src','/web/kaptcha.jpg?'+Math.floor(Math.random()*100));\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <div style=\"text-align:left;margin-bottom:20px;margin-left:13%;\">\r\n");
      out.write("                                <input type=\"checkbox\" /><span style=\"font-size:12px; color:#CCC;\">记住登记状态</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div ng-click=\"login()\" style=\"cursor: pointer;margin:0 auto;margin-bottom:20px;border-radius:10px;text-align:center;width:74%;height:30px;padding-top:2px;background-color:#5A8ED1;font-size:18px;border-radius:8px;color:#fff\">\r\n");
      out.write("                                登&nbsp;&nbsp;录\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td  width=\"20%\" style=\"width:20%;\">\r\n");
      out.write("                    <img src=\"");
      out.print(root);
      out.write("/website/show/img/homeright.png\" style=\"width:100%;height:300px;\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr style=\"background-color: #FFFFFF;\">\r\n");
      out.write("        <td ></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr  style=\"height:100px;\">\r\n");
      out.write("        <td >\r\n");
      out.write("            <div class=\"footer\">\r\n");
      out.write("                <div style=\"color: #ffffff;font-size: 12px;position:fixed; bottom:0; left:0;width:100%;\">\r\n");
      out.write("                    ©2020&nbsp;版权所有:昆山医疗保障局\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- END Lock Screen Content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Apps Modal -->\r\n");
      out.write("<!-- Opens from the button in the header -->\r\n");
      out.write("<div class=\"modal fade\" id=\"apps-modal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-sm modal-dialog modal-dialog-top\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <!-- Apps Block -->\r\n");
      out.write("            <div class=\"block block-themed block-transparent\">\r\n");
      out.write("                <div class=\"block-header bg-primary-dark\">\r\n");
      out.write("                    <ul class=\"block-options\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <button data-dismiss=\"modal\" type=\"button\"><i class=\"si si-close\"></i></button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <h3 class=\"block-title\">Apps</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"block-content\">\r\n");
      out.write("                    <div class=\"row text-center\">\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                            <a class=\"block block-rounded\" href=\"base_pages_dashboard.html\">\r\n");
      out.write("                                <div class=\"block-content text-white bg-default\">\r\n");
      out.write("                                    <i class=\"si si-speedometer fa-2x\"></i>\r\n");
      out.write("                                    <div class=\"font-w600 push-15-t push-15\">Backend</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                            <a class=\"block block-rounded\" href=\"frontend_home.html\">\r\n");
      out.write("                                <div class=\"block-content text-white bg-modern\">\r\n");
      out.write("                                    <i class=\"si si-rocket fa-2x\"></i>\r\n");
      out.write("                                    <div class=\"font-w600 push-15-t push-15\">Frontend</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END Apps Block -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END Apps Modal -->\r\n");
      out.write("\r\n");
      out.write("<!-- Pop Out Modal -->\r\n");
      out.write("<div class=\"modal  fade\" id=\"modal-popout\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-popout\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"block block-themed animated fadeIn\">\r\n");
      out.write("                <div class=\"block-content block-content-full block-content-narrow\">\r\n");
      out.write("                    <form class=\"js-validation-login form-horizontal push-30-t push-50\" action=\"base_pages_dashboard.html\" method=\"post\" novalidate=\"novalidate\">\r\n");
      out.write("                        <div class=\"form-group\" style=\"display: none;\">\r\n");
      out.write("                            <div class=\"col-xs-12\">\r\n");
      out.write("                                ");
      if (_jspx_meth_e_005fnumber_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- END Login Form -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END Pop Out Modal -->\r\n");
      out.write("\r\n");
      out.write("<!-- OneUI Core JS: jQuery, Bootstrap, slimScroll, scrollLock, Appear, CountTo, Placeholder, Cookie and App.js -->\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/jquery.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/bootstrap.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/jquery.slimscroll.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/jquery.scrollLock.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/jquery.appear.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/jquery.countTo.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/jquery.placeholder.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/js.cookie.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/website/show/home.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    jQuery(function () {\r\n");
      out.write("        // Init page helpers (Appear + CountTo plugins)\r\n");
      out.write("        JQueryApp.initHelpers(['appear', 'appear-countTo']);\r\n");
      out.write("        JQueryApp.initHelpers('magnific-popup');\r\n");
      out.write("        JQueryApp.initHelpers('slick');\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/frame/resource/js/plugins/slidereveal/slidereveal.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script> <!-- 左侧划出窗口 -->\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/frame/resource/js/plugins/bootstrap-notify/bootstrap-notify.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>    <!-- 错误提示 -->\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/frame/resource/js/plugins/screenfull/screenfull.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>   <!-- 全屏 -->\r\n");
      out.write("\r\n");
      out.write("<!-- OneUI Core JS: AngularJS -->\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/angular.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/frame/resource/js/plugins/fileupload/ng-file-upload.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>  <!-- 文件上传 -->\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/angular-ui-router.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/plugins/ui-bootstrap-tpls/ui-bootstrap-tpls-2.3.1.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/angular-scroll.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/ocLazyLoad.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/ngStorage.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- OneUI Core JS: Kendo -->\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/kendo.all.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/frame/resource/js/plugins/resizable/Resizable.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/core/kendo.poptextbox.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Page JS Plugins -->\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/plugins/magnific-popup/magnific-popup.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/website/show/app.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/factorys.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/directives.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/assets/js/plugins/slick/slick.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/website/show/resource/js/jquery.validate.min.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      out.print(root);
      out.write("/website/show/login.js?jsVersion=");
      out.print(jsVersion);
      out.write("\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_e_005fhidden_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:hidden
    com.eframework.web.tags.HiddenTag _jspx_th_e_005fhidden_005f0 = (new com.eframework.web.tags.HiddenTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fhidden_005f0);
    _jspx_th_e_005fhidden_005f0.setJspContext(_jspx_page_context);
    // /website/show/login.jsp(165,0) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fhidden_005f0.setName("frameControlOption");
    _jspx_th_e_005fhidden_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fhidden_005f0);
    return false;
  }

  private boolean _jspx_meth_e_005fnumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:number
    com.eframework.web.tags.NumbFieldTag _jspx_th_e_005fnumber_005f0 = (new com.eframework.web.tags.NumbFieldTag());
    _jsp_instancemanager.newInstance(_jspx_th_e_005fnumber_005f0);
    _jspx_th_e_005fnumber_005f0.setJspContext(_jspx_page_context);
    // /website/show/login.jsp(283,32) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fnumber_005f0.setName("aaaa");
    // /website/show/login.jsp(283,32) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_e_005fnumber_005f0.setLabel("abc");
    _jspx_th_e_005fnumber_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_e_005fnumber_005f0);
    return false;
  }
}
